import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.Completion.create(
  engine="text-babbage-001",
  prompt="Provide 7 tips for making better YouTi I love Kuki\n\n\n1.",
  temperature=0.7,
  max_tokens=150,
  top_p=1,
  frequency_penalty=0.49,
  presence_penalty=0
)
